### ISSUE TITLE
Please enter a valid xmpp address

### ISSUE THREAD

**Issue by roughnecks** [conversejs/roundcube-plugin#20]
Hi,

that's what it tells me when I try to login, whether I write my username alone or my full JID.

I'm trying this with latest roundcube release, 1.6.4 and with `https://cdn.conversejs.org/10.1.6`

**Comment by drlight17** [comment]
Hello.
Please, show your config. Are there any errors in browser console?
Does this error error appear in previous CDN versions of Converse.js?

**Comment by roughnecks** [comment]
I was able to login, but had to use CDN 10.1.2 to make it fetch MAM and send messages, otherwise it was all stuck.
Also, it looks like there's a pletora of errors in console.

This one repeats every now and then:
```
ERROR: Tempo scaduto tentando di raccogliere i messaggi archiviati.
log @ converse.js:20346
error @ converse.js:20361
query @ converse.js:34457
```
While I got lots of these:
```
Uncaught (in promise) Error: Timeout error after 20000ms for the following IQ stanza: <iq id="8b436660-41ff-4885-9054-fe4ffc3cf7bd:sendIQ" to="operators@muc.xmpp.org/Chris Mac" type="get" xmlns="jabber:client"><vCard xmlns="vcard-temp"/></iq>
    at converse.js:25056:19
```

**Comment by jcbrand** [comment]
Timeout errors for VCards aren't that uncommon and isn't related to the original issue you reported here.

**Comment by roughnecks** [comment]
Alright, what about MAM timing out?

**Comment by drlight17** [comment]
> I was able to login, but had to use CDN 10.1.2 to make it fetch MAM and send messages, otherwise it was all stuck. Also, it looks like there's a pletora of errors in console.
> 
> This one repeats every now and then:
> 
> ```
> ERROR: Tempo scaduto tentando di raccogliere i messaggi archiviati.
> log @ converse.js:20346
> error @ converse.js:20361
> query @ converse.js:34457
> ```
> 
> While I got lots of these:
> 
> ```
> Uncaught (in promise) Error: Timeout error after 20000ms for the following IQ stanza: <iq id="8b436660-41ff-4885-9054-fe4ffc3cf7bd:sendIQ" to="operators@muc.xmpp.org/Chris Mac" type="get" xmlns="jabber:client"><vCard xmlns="vcard-temp"/></iq>
>     at converse.js:25056:19
> ```

Well, current 0.9.1 version of plugin were tested on the very last version of CDN for the moment - 10.1.2. Now there is need for some newer CDN versions tests. I will check this out when there will be less busy time.

**Comment by roughnecks** [comment]
Thanks!
